language: python
python:
- '2.7'
env:
  global:
    - secure: "Ewud3hGfwNN44mosPPQA0hqHB99K1SnQ2zS84LFtVxKbNjOu7CTQ8GjK3LkFHFkhLh0WjjwMf4fBwPuDovjT0BpPiGG7sIQ3P4Bp6E4lONy9pLXhT1yK2g9ZM6qsz/Db9fFyiYLveZmaEoy3De9sCvei1YnpyLQ0GhRpo+LsNdd9V20lWC4U2b7jPIcrgJy9Z65DT9qNNMBqoe/S2irkxpNk/Trl+9JVqHK0roKsgrfb8kNOL/rKU1zgxicy1FfBquPY0CIcTc7bC2EaOGY/xtLN7d0cVxTjME9L90dc/1mpU4EKptu15xj/R32+WUmVgWs1fjrs2uKY59+4GO7+SCM3cjWd9Gh6LN6Ci6SuP2Hu+aV1UQg0C411t2xcUttaXyRMd9u1ud39omrEhAphtmvrK+iUwmxMepIcbIzZFDCxid/M6wDaDf/6HpCrdgB+AlDRBK/vAAHtCpvpYymRVbtFJAkZotlGaUUx/uolKCJ54bn6jeNylvEvk0AdU1nDFw5I4NxFDWf9IHfpzOXCZExp2IHZ91Ifejb4cvioxh9mrXv0tA7UyPqc8odcDqgJ2P+/ipmF2sClhq6ttL5nG3hmylOY3SGhgKpI/f3S0HCOoBbHfpdn5cE05F4v6P+DabxVftQFT4VbHHcEBhaaSL3FzUzrihXTtCV6y/L/Kd0="
    - ES_VERSION=2.3.2
addons:
  apt:
    packages:
      - gcc
      - make
      - libxml2-dev
      - libxslt-dev
      - libjpeg8-dev
      - libopenjpeg-dev
      - libwebp-dev
      - libmysqld-dev
      - libldap2-dev
      - libsasl2-dev
      - libpcre3-dev
      - libtiff4-dev
      - libpq-dev
cache:
  directories:
  - $HOME/.cache/pip
before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch -d -D es.path.data=/tmp -D es.discovery.zen.ping.multicast.enabled=false"
install:
- pip install --upgrade pip
- easy_install -U setuptools
- pip install Babel configobj dateutils docutils flup lxml Pillow pycrypto python-memcached pytz oauth2 requests webob xlwt
- easy_install .
- pip install elasticsearch
- pip install sphinx
- pip install coveralls
script:
- cd doc && make html && cd ../
- python setup.py compile_catalog
- coverage run --source=kansha --timid setup.py nosetests
after_success: coveralls
deploy:
  - provider: pypi
    user: Net-ng
    password:
      secure: c9jMMtFUVRs+JGPBr4WunK1ziky/1GJbrqe7JqMBHnDXXvbr2xOXvmhOB/hvZghdrXDkAopjcsCYUDdU0maS1AcM7y8YGNl6HbfD3ZWJVCcIIW+2HWKseNxTo9Mh2Iai4EL+ty8bFC4T4XKA1bpGPS+/cW30Qekj6t7nWKFqDuBz70zW1a/FekvyZYw6hs6mBr68ouGfip1C5khy+ceDx49ElI1KVXAiIXgjp3b5Z8tCmVuD3+7sLPsOh0X4USyJlHlg5uz734Te8IzaMPfd30U2ZnPd8SxPaJivB9CgVrlzytaVWAgTzsucnTJJ6Fgg8ec2iD57Q3DYA1sOozRuMlSI4vZ/CLO+jG1wQd91dNly1X23gGiGX85xXkxgoFxgF5XrAsG9pvf76ACKb8zT+6DduGW37gxdZqWZZvZ5A8ysHf4cGAc9Ain0newjfZheu6p+Cw0St4FjTZqNdhujUbEcT0D+uD/hCcjeXUMp79Q3x770NEEVeFpU7EjKfmc3TrlKr+rVSVd5WhHM1J2oV2aM8gO1n/UI77H9b9fI8tfC+SoykagOJ64xSTuWUdi3nGOZpGsjC3uVRlBbQy1Jv4A5slIzdJZ4rlqggyBdPeCpNAc5URzWEktSQqIzYaaVVdejfIf0bfyBm2/4r7TqRD9fZap72BwqLiyGBFjqR7w=
    on:
      branch: release
  - provider: script
    script: scripts/docker_deploy.sh
    on:
      branch: release
sudo: false
